### ISSUE TITLE
Push Notifications support for OS X, tvOS

### ISSUE THREAD

**Issue by flovilmart** [parse-server-modules/parse-server-push-adapter#11]
This issue is for tracking an improvement to classic ParsePushAdapter to add support for OS X (which is supported on classic Parse), and tvOS (which is not).

Adding support for these would be very trivial, since we have iOS Push Notifications working, and would require changes to a few things:
- Add support for osx and tvos deviceTypes to installation
- Add support to ParsePushAdapter and APNS.js to accept more than just iOS certificates.
- Add support to ParsePushAdapter and APNS.js to send to tvOS, which reuses the same certificate as iOS.
  Comment here, subscribe to this issue or send a PR to implement any part of this.

Originally ParsePlatform/parse-server#571

cc: @nlutsenko

**Comment by nlutsenko** [comment]
The device types for tvOS/watchOS that are being sent and used in the SDK:
- `appletv`
- `applewatch`

This means that whenever we add support for push on these platforms - we should reuse the same device types to support easier migration.

**Comment by funkenstrahlen** [comment]
Any news on this? I would love to see this implemented!

**Comment by phranck** [comment]
Oh wow! This issue hangs around for a near now. I really would love it too if we can receive push notifications on macOS. Please go for it... ☺️

**Comment by flovilmart** [comment]
That should be pretty trivial to implement, if anyone wants to go for it, go ahead!

**Comment by funkenstrahlen** [comment]
@flovilmart I will take a look at it. Are you able to help in case I have questions on how to implement this?

**Comment by flovilmart** [comment]
Yep, no problem :)

**Comment by flovilmart** [comment]
Closing as fixed with #58
