### ISSUE TITLE
apns feedback service

### ISSUE THREAD

**Issue by diwu1989** [parse-server-modules/parse-server-push-adapter#13]
please add in support for the apns feedback service so that periodically, deregistered devices are cleaned out of the database, thankyou!

**Comment by tarekskr** [comment]
+1

**Comment by Droppix** [comment]
+1

**Comment by flovilmart** [comment]
There's no need for the feedback service anymore, if you're using the latest parse-server you can set `PARSE_SERVER_CLEANUP_INVALID_INSTALLATIONS=1` and it will remove the invalid device tokens ('Unregistered' ||  'BadDeviceToken')

https://github.com/parse-community/parse-server/blob/master/src/StatusHandler.js#L198
