### ISSUE TITLE
New release for `mutableContent`

### ISSUE THREAD

**Issue by alexanderedge** [parse-server-modules/parse-server-push-adapter#28]
Hi there,

Is it possible to cut a new release for the latest changes that support `mutable-content` in APNS? Presumably this will be version `1.1.0` as the interface has changed. Shall I submit a PR?

Thanks in advance

**Comment by alexanderedge** [comment]
Hi @flovilmart, is there anything I can do to assist in creating a new release? Thanks

**Comment by flovilmart** [comment]
Go for the PR :) sorry for the delay

**Comment by alexanderedge** [comment]
No problem, opened #30
