### ISSUE TITLE
How to develop new Push sender - MQTT

### ISSUE THREAD

**Issue by Sharathmk99** [parse-server-modules/parse-server-push-adapter#29]
Hi,

I need to use push notification without GCM/APN, so decided to develop using MQTT.
Please help me how to proceed

Thanks
Sharath

**Comment by natanrolnik** [comment]
@Sharathmk99 this repo is the Parse Server **push notifications adapter for GCM and APNS**. If you need to implement MQTT in your Node app, I guess that https://www.npmjs.com/package/mqtt is what you are looking for...
