### ISSUE TITLE
Add support for new "mutable-content" iOS 10 flag

### ISSUE THREAD

**Issue by timonus** [parse-server-modules/parse-server-push-adapter#34]
Similar to "content-available" from iOS 7, but this flag is used to inform the OS that a notification service extension should be woken up to do some work.

Relevant WWDC talk from this year: https://developer.apple.com/videos/play/wwdc2016/708/

**Comment by timonus** [comment]
Oh wait, it's here https://github.com/parse-server-modules/parse-server-push-adapter/blob/76383d9243f6c2cdae82e92d8e7a6e64ca3bcdfb/src/APNS.js#L239.

**Comment by flovilmart** [comment]
Yup! And released too :)
