### ISSUE TITLE
ERR! parse-server-push-adapter GCM send errored: 401

### ISSUE THREAD

**Issue by Heman6886** [parse-server-modules/parse-server-push-adapter#45]
<img width="435" alt="untitledguthub" src="https://cloud.githubusercontent.com/assets/12099245/20424791/a7735c82-ad9d-11e6-835f-1d398fa2cca5.png">
My Server was Working Fine but From some days the notification was not recieved to my devices so i check whole github and stackoverflow and was unablw to find any solution so if anybody knows how to fix this

**Comment by max-at-brili** [comment]
Have you tried resetting your GCM API Key or switching to using a FCM ID and token? https://developers.google.com/cloud-messaging/

**Comment by tru3d3v** [comment]
Hi, its happen to me. 

ERR! parse-server-push-adapter GCM send errored: 401
