### ISSUE TITLE
Could we have Firebase Cloud Messaging (FCM)?

### ISSUE THREAD

**Issue by uluru-phatnguyen** [parse-server-modules/parse-server-push-adapter#46]
Hi @flovilmart

Can you support for me about Firebase Cloud Messaging (FCM).

Thanks.

**Comment by flovilmart** [comment]
FCM should be 100% compatible with GCM. So it should be supported out of the box

**Comment by uluru-phatnguyen** [comment]
@flovilmart 
Thanks for your reply soon.

But It's not stable when we used GCM, maybe we lost 50% notifications when used FCM.

We changed to use GCM, It's stable.

I don't know why.

**Comment by flovilmart** [comment]
closing as a large discussion on FCM support is happening on the android SDK repository. https://github.com/parse-community/Parse-SDK-Android/issues/572
