### ISSUE TITLE
push notification to  channels except  the current user

### ISSUE THREAD

**Issue by pastordee** [parse-server-modules/parse-server-push-adapter#59]
Hi I'm new to parse how can the user send a post and not receive the  notification him self

 var theMessage = request.params.message;
    var theChannel = request.params.channels;
    var theView = request.params.view;
    var theTitle = request.params.thetitle;
    var pushQuery = new Parse.Query(Parse.Installation);
    pushQuery.equalTo('channels', theChannel);
    pushQuery.notEqualTo('user', request.params.user);
   Parse.Push.send({
	   			  where: pushQuery,
                  data: {
	                title: theTitle,
                    alert: theMessage,
                    view:	theView,
                    badge: 1,
                    sound: 'default'
                  }
                }, { useMasterKey: true }).then(function(){
                  response.success('Push ok');
                }, function(error){
                  response.error('Push error');
        });

This works fine but the sender also receives the push notifications.

**Comment by funkenstrahlen** [comment]
Your query runs on `PFInstallation` objects. Therefore `pushQuery.notEqualTo('user', request.params.user);` has no effect at all.

**Comment by flovilmart** [comment]
Hi this issue should be opened on parse-server, can you update to latest parse-server version (2.5.1) and reopen the issue on the parse-server repo if it persists?
