### ISSUE TITLE
Support title payload on iOS notifications

### ISSUE THREAD

**Issue by gfpacheco** [parse-server-modules/parse-server-push-adapter#73]
About the push notification title parameter, the docs says it's only sent to Android devices, but it's supported since [iOS 8.2](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW5).

I was wondering if Parse really doesn't send it for iOS devices or it's just the docs that are outdated, but I couldn't find any mention to it in the source files.

Is it planned or was it discarded for some reason? Should I try to make a PR?

**Comment by flovilmart** [comment]
I'm not sure, but title is a property of "alert" when you set it as a dictionary, and it's just passed as-is: https://github.com/parse-server-modules/parse-server-push-adapter/blob/master/src/APNS.js#L177

**Comment by natanrolnik** [comment]
It can be done already as @flovilmart suggested.
